Readify/madskillz

- README.md
As per the discussion in https://github.com/Readify/madskillz/issues/34
> Update Readme with levelling up changes

- Consulting.md
This pivots into some 'soft skills' but none of us should be working in a vacuum.
> Devs should be writing the correct code

- README.md
I end up regularly having discussions of what Outstanding means in the context of Readify and trying to level-set expectations.
The main issue is that we tend to compare ourselves against the rest of the industry. We already aim to hire the best of the best, the top 10% as it were, in which case most of us should just tick outstanding on everything :-) I want to clarify that we're talking about Outstanding in the context of ourselves compared to our peers. How do we stack up against the rest of Readify? In what areas do we think we're the best of the best of the best?
So, if you're good at something? No brainer. 
If you're really good at something? Still a no-brainer; that's Readify 'standard' expectations.
If you're really, really, really good and others in Readify look at your skills as …
> Clarify the Outstanding rating to reduce confusion

- Consulting.md
I don't think we need to link anywhere - this document shouldn't be tied back to our marketing site for reference. If people don't know what our values are, that is a separate discussion.
> Removing Unconventional

- Consulting.md
My take on the communication criteria.
> Alternate take on communication criteria

- Consulting.md
Being more specific around expected levels of communication ability, focusing on writing but as we head up the Consulting path, this branches out into general persuasion and handling difficult communication situations.
> Added criteria specific to written communication

- Managed Services.md
Removing duplication for mundane tasks.
> Removing duplication for mundane tasks.

- Managed Services.md
I performed my last review against MadSkillz and didn't like the wording of a few points for the Technical Leads. I have tried to clean this up.
> Update Technical Lead wording

- Consulting.md
> defense to defence

- Consulting.md
An SC might not be mentioning a developer as such as any Readifarian want to learn a particular skill.
> Update SC mentoring reference

- Consulting.md
wether = whether
consultanting = consulting
> Spelling mistakes in PC

- README.md
consenus = consensus
wether = whether
> Spelling mistakes in Readme.md

- Engineering.md
Stack Overflow has a space. Skills doesn't have a Z (and yes I see humour with this).
> Fix spelling mistake in SE

- Consulting.md
Sustained Systems Engineer had some additional text around learning methods, merging these into Developer.
> Update Developer learning methods

- Consulting.md
I don't understand why diving head first on most difficult problems is a desired approach.
> The most difficult problems

- Consulting.md
Updated wording around communications style, also removed help desk reference as that is so 90s.
> Update PC to better cover working with other teams

- Engineering.md
* Improve first technical knowledge sentence. 
* Split the awkward and/or combination of 'open source' and 'desired team member' into two separate points.
> Senior Engineer technical knowledge improvements

- Consulting.md
Fixed some wording to emphasize being a proactive supporter of a technical direction, not only follower of whatever change customer want to proceed with.
> Changing requirements

- Consulting.md
The main reason for that is I found business agility missing in the role description. I find those skills useful when working with customer and worth putting explicitly into the role difinition
> Added a line about supporting teams and customers in setting up and measuring initiative success criteria

- Consulting.md
Address the issue raised by Meligy #53 about the wording for this line. I've expanded it to address "difficult conversations" in general, beyond just challenging others.
> Clarify and expand on "richer for the experience" in SC role

- Consulting.md
Adding graduate developer mad skillz
> Grad developer

- Managed Services.md
All looks ok but I think Technical Leads are also expected to identify problems early and engage relevant people.
> Technical Leads are also expected to identify problems and engage

- Consulting.md
Doing my retros I've found that 'I am proficient at delivering software projects using agile practices.' is ambiguous. I'm wondering if we can have a discussion on how to clarify agile MadSkillz in a way that we can more clearly define the responsibilities of an SD, SC, LC.
> 'Agile' MadSkill distinction between SD, SC and LC

- Development.md
- Engineering.md
- Managed Services.md
- README.md
We have consultants across many practices
> Incorporate 'Development' department

- Development.md
- Managed Services.md
Removing incorrect text related to managed services roles.
> Removing incorrect text around managed services roles.

- Engineering.md
Per Alison request, new _Lead Engineer_ section is added under _Engineering_.
> Added Lead Engineer

- Engineering.md
- Removed some duplication / redundancies between the title, examples, and SE definition
- Tightened up a few statements to make them more concise
- Oxford commas!
- Completed a sentence that was missing its tail
- Expanded an acronym to make it clearer to public viewers
> Editing pass over Lead Engineer definition

- Engineering.md
This language change avoids the implication of SE's needing a "personal brand", and focuses more on the attributes we want them to demonstrate.
Addresses #73
> Changed language around engineering community engagement.

- README.md
Attempts to address #102 - however probably needs a little more refinement
> Provide examples of defining characteristics vs examples

- Engineering.md
addresses some of the points in #109
> Improves the tone of engineering pathway

- Engineering.md
> I am more than a Senior Developer
This is not the right language. No one is more than others in such a blanket statement way.
> Focusing on technical excellence as opposed to comparison with SD role

- LICENSE.md
> add Creative Commons Attribution-ShareAlike 4.0 International Public License

- Development.md
Just fixing a small grammar mistake.
> Correct "mine team" to "my team".

- README.md
Fix Typo: a either > either, a because > because
> Fix Typo: a either > either, a because > because
